import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import { Button, Input, Select } from 'antd'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>{' '}
      <Select
        placeholder="helloe world"
        options={[{ label: 'dsds', value: 'dsdas' }]}
      />
      <Input placeholder="helloe world" />
      <Button type="primary">button </Button>
    </>
  )
}
